/**
 * `yap init` — scaffold the yap home directory with a generated config.
 * Explicit by design: keys are minted only when the operator asks, never as a
 * startup side effect, and an existing .env is never touched.
 */
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { generateSecret } from "../crypto.js";

export interface InitResult {
  envPath: string;
  /** False when an .env already existed (nothing was written). */
  created: boolean;
  /** Empty when created is false. */
  sysadminKey: string;
}

export function initYapHome(home: string): InitResult {
  const envPath = join(home, ".env");
  if (existsSync(envPath)) return { envPath, created: false, sysadminKey: "" };

  mkdirSync(join(home, "data"), { recursive: true });

  const sysadminKey = generateSecret("yap_sys_");
  const masterKey = randomBytes(32).toString("base64");
  const content = `# Generated by \`yap init\`. Real environment variables override these.
# Full list of options: https://github.com/yap-tools/yap-core (README) or
# the .env.example shipped with the package.

# Environment credential for user provisioning over REST (never MCP).
YAP_SYSADMIN_KEY=${sysadminKey}
# Base64-encoded 32 bytes: hook-secret encryption + link/token signing.
# Changing it orphans encrypted hook secrets and invalidates minted links.
YAP_MASTER_KEY=${masterKey}

YAP_SQLITE_PATH=${join(home, "data", "yap.db")}
YAP_BLOB_FS_ROOT=${join(home, "data", "blobs")}

# YAP_PORT=8787
# Public origin for minted links and the OAuth issuer — set this when the
# instance is reachable from other machines (https except on loopback).
# YAP_BASE_URL=http://localhost:8787
`;
  writeFileSync(envPath, content, { mode: 0o600 });
  return { envPath, created: true, sysadminKey };
}
