/**
 * `yap init` — scaffold a Yap instance in a directory. Explicit by design:
 * keys are minted only when the operator asks, never as a startup side
 * effect, and an existing .env is never touched. Data paths are written
 * relative to the instance directory so the whole instance stays
 * relocatable; `yap` is expected to run from inside it.
 */
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { generateSecret } from "../crypto.js";
import { dataDir, envPath as instanceEnvPath } from "../instance/layout.js";

export interface InitResult {
  envPath: string;
  /** False when an .env already existed (nothing was written). */
  created: boolean;
  /** Empty when created is false. */
  sysadminKey: string;
}

export function initInstance(dir: string, options: { port?: string } = {}): InitResult {
  const envPath = instanceEnvPath(dir);
  if (existsSync(envPath)) return { envPath, created: false, sysadminKey: "" };

  mkdirSync(dataDir(dir), { recursive: true });

  const sysadminKey = generateSecret("yap_sys_");
  const masterKey = randomBytes(32).toString("base64");
  const content = `# Generated by \`yap init\`. Run \`yap\` from this directory to serve this
# instance. Real environment variables override these. Full list of options:
# https://github.com/yap-tools/yap-core (README, .env.example).

# Environment credential for user provisioning over REST (never MCP).
YAP_SYSADMIN_KEY=${sysadminKey}
# Base64-encoded 32 bytes: hook-secret encryption + link/token signing.
# Changing it orphans encrypted hook secrets and invalidates minted links.
YAP_MASTER_KEY=${masterKey}

# Paths resolve relative to this directory.
YAP_SQLITE_PATH=./data/yap.db
YAP_BLOB_FS_ROOT=./data/blobs

# Give each instance on this machine its own port.
${options.port ? `YAP_PORT=${options.port}` : "# YAP_PORT=8787"}
# Public origin for minted links and the OAuth issuer — set this when the
# instance is reachable from other machines (https except on loopback).
# YAP_BASE_URL=http://localhost:8787
`;
  writeFileSync(envPath, content, { mode: 0o600 });

  // Keys, data, the CLI credential, and the vendored server must never land
  // in version control if the instance directory becomes a repo.
  const gitignorePath = join(dir, ".gitignore");
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, "# Yap instance state — keep keys and data out of version control\n.env\n.yap/\ndata/\nnode_modules/\n");
  }

  return { envPath, created: true, sysadminKey };
}
